baseURL = ""
languageCode = "en-us"
title = "World Bank Data Lab"
assetDir = "static/assets"

[params]
	dataResourcesLinkTitle = "Data Resources"
	dataResourcesLink = "/data-resources-directory"

	externalPartnershipsLinkTitle = "Find External Collaborators"

	dataPartnershipsLinkTitle = "Development Data Partnership"
	dataPartnershipsLink = "https://datapartnership.org"

	workshopsSectionLabel = "Workshops and Events"

	dataDirectoryLabel = "Find World Bank Data Resources"

	dataDirectoryPageLabel = "WB Data Directory"

	dataLeadsLabel = "Data Lab Leads Network"

	DataLabEmail = "mailto:datalab@worldbank.org"
	DataLabMailingList = "mailto:datalab@worldbank.org?subject=Add%20Me%20to%20the%20Data%20Lab's%20Mailing%20List"
	DataLabRequestForm = "https://forms.office.com/r/xC05GdvTNU"
	DataLabRequestFormTracker = "https://worldbankgroup-my.sharepoint.com/:x:/r/personal/ccalderon2_worldbank_org/Documents/Data%20Lab%20Website/data%20lab%20request%20for%20support.xlsx?d=w75ce08e79cb1454d9378b2cc10bea9bb&csf=1&web=1&e=pGdpMC"
	DataLabDirectory = "https://worldbankgroup-my.sharepoint.com/personal/ccalderon2_worldbank_org/_layouts/15/Doc.aspx?sourcedoc={cbf7d856-fbbb-45e7-ad75-de5446aea8d0}&action=embedview&ActiveCell='WebDisplay'!A1&Item='WebDisplay'!A1%3AE120&wdDownloadButton=True&wdInConfigurator=True"


[module]
	[hugoVersion]
	extended = true

[taxonomies]
	workshop_types = "workshop_types"
	teams = "teams"
