baseURL = ""
languageCode = "en-us"
title = "World Bank Data Lab"
assetDir = "static/assets"

[params]
	dataResourcesLinkTitle = "Data Resources"
	dataResourcesLink = "/data-resources-directory"

	externalPartnershipsLinkTitle = "Find External Collaborators"

	dataPartnershipsLinkTitle = "Development Data Partnership"
	dataPartnershipsLink = "https://datapartnership.org"

	workshopsSectionLabel = "Workshops and Events"

	dataDirectoryLabel = "Find World Bank Data Resources"

	dataDirectoryPageLabel = "WB Data Directory"

	dataLeadsLabel = "Data Lab Leads Network"
	dataLeadsLink = "/data-leads"

	dataCorpsLabel = "Data Corps"
	dataCorpsLink = "/data-corps"

	universityDataFellowsLabel = "University Data Fellows"
	universityDataFellowsLink = "/university-data-fellows"

	DataLabRequestForm = "https://forms.office.com/r/xC05GdvTNU"
[module]
	[hugoVersion]
	extended = true

[taxonomies]
	workshop_types = "workshop_types"
	teams = "teams"
